spring.application.name=horarios
spring.jpa.hibernate.ddl-auto = create
spring.datasource.url=jdbc:postgresql://localhost:5432/horarios
spring.datasource.username=postgres
spring.datasource.password=${db_password}
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


